grupa_video_net_index_default:
    path:     /
    defaults: { _controller: GrupaVideoNetBundle:Index:index }

grupa_video_net_index:
    path:     /index
    defaults: { _controller: GrupaVideoNetBundle:Index:index }

grupa_video_net_contact:
    path:     /kontakt
    defaults: { _controller: GrupaVideoNetBundle:Contact:contact }

grupa_video_net_films:
    path:     /films/{category}/{sort}/{direction}/{page}
    defaults: { _controller: GrupaVideoNetBundle:Films:filmsIndex, category: "all", sort: "name", direction: "desc", page: 1  }
grupa_video_net_films_view:
    path:     /films/view/{id}
    defaults: { _controller: GrupaVideoNetBundle:Films:filmsView }

grupa_video_net_forum:
    path:     /forum
    defaults: { _controller: GrupaVideoNetBundle:Forum:forumIndex }
grupa_video_net_forum_section:
    path:     /forum/section/{section_id}/{page}
    defaults: { _controller: GrupaVideoNetBundle:Forum:forumSection, page : 1}
grupa_video_net_forum_topic:
    path:     /forum/section/{section_id}/topic/{topic_id}/{page}
    defaults: { _controller: GrupaVideoNetBundle:Forum:forumTopic, page : 1}

grupa_video_net_profile_view:
    path:     /profile/view/{id}
    defaults: { _controller: GrupaVideoNetBundle:ProfileView:profileView }

grupa_video_net_admin_movie_add:
    path:     /admin/movie/add
    defaults: { _controller: GrupaVideoNetBundle:Admin\MovieAdd:movieAdd }

